added html css and Script File
nasir-k/Contact-App pull request #1
Opened 2022-01-22 14:28 UTC by nasir-k

2022-01-22 14:38 UTC, faran4engg commented on app.js
> +const closecontactModal = () => {
can we use the naming convention properly? In camel case it should be `closeContactModal`

2022-01-22 14:38 UTC, faran4engg commented on app.js
> +const addcontactModal = () => {
same here @nasir-k

2022-01-22 19:54 UTC, faran4engg commented on index.html
> +        <input type="text" name="First Name" id="First-Name" />
I would not give value to the `name` attribute with space !

2022-01-22 19:55 UTC, faran4engg commented on index.html
> +        <input type="number" name="phone" id="" step="10" />
what does the step do ?

2022-01-22 19:56 UTC, faran4engg commented on style.css
> +  font: inherit;
why inherit ?

2022-01-22 19:57 UTC, faran4engg requested changes
I have same review comments as Abbas's PR, could you check those and correct please !

2022-01-23 08:37 UTC, syedabdullahali approved these changes

2022-01-27 21:15 UTC, merged